name: Fix TDLib

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout ZapZap
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Restore original .so files
        run: |
          git checkout 29393364dd4d4fb3177f7b40012c8970a50de6ba -- android/app/src/main/jniLibs/
          ls -lh android/app/src/main/jniLibs/arm64-v8a/

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add android/app/src/main/jniLibs/
          git diff --staged --quiet || git commit -m "Fix: restore original libtdjni.so"
          git push
