name: Restore TDLib

on:
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout ZapZap
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Restore original libtdjni.so
        run: |
          git log --oneline -5
          # Volta os .so para o commit anterior ao update_tdlib
          git checkout HEAD~1 -- android/app/src/main/jniLibs/
          echo "Restored!"

      - name: Commit restored TDLib
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add android/app/src/main/jniLibs/
          git diff --staged --quiet || git commit -m "Restore original libtdjni.so"
          git push
